services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql-ultimate-course
      MYSQL_USER: joey
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./datasets/mysql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    