services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: MyPassword123!
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P MyPassword123! -C -Q "SELECT 1"
      interval: 30s
      timeout: 10s
      retries: 5

  sqlserver-init:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./datasets/sql-server:/scripts
    command: |
      /bin/bash -c "
      echo 'Running SQL initialization scripts...'
      for file in /scripts/*.sql; do
        if [ -f \"\$$file\" ]; then
          echo \"Executing \$$file...\"
          /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P MyPassword123! -C -i \"\$$file\"
        fi
      done
      echo 'Database initialization complete!'
      "

volumes:
  sqlserver_data:
    